

[alias]
lint = "clippy --all-targets"
benchmarks = "bench --features benchmarks --locked"
ntest = "nextest run --locked"
coverage = "llvm-cov --workspace --codecov --output-path codecov.json"
t = "nextest run --locked"
